Ankurshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
import shop

# from shop import urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("shop/", include("shop.urls", namespace="shop")),
    path("accounts/", include("allauth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("api-auth/", include("rest_framework.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

# swagger imports
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views
from .views import (
    ProductViewSet,
    CategoryViewSet,
    OrderViewSet,
    AdressViewSet,
    WishlistViewSet,
    SearchListView,
)


schema_view = get_schema_view(
    openapi.Info(
        title="Ankurshop",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="Test License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

router = routers.DefaultRouter()
router.register(r"Products", ProductViewSet)
router.register(r"Category", CategoryViewSet)
router.register(r"Adress", AdressViewSet)
router.register(r"Order", OrderViewSet)
router.register(r"Wishlist", WishlistViewSet)
# router.register(r"search",ProductListView)


urlpatterns = [
    path("", include(router.urls)),
    path("search/", SearchListView.as_view(), name="search"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    #  path("gettoken/", obtain_auth_token),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # path('^swagger(?P<format>\.json|\.yaml)', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # path("wishlist",listWishlist.as_view(),name="wishlist"),
]

shop/urls.py
from django.urls import path
from .views import Index
from shop import views
from . import views
from shop import models


urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("Payment", views.Payment, name="Payment"),
    path("succes", views.Succes, name="succes"),
    path("search/", views.Search, name="search"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path("checkout", views.CheckoutCreateView.as_view(), name="checkout-page"),
    # urls for cart
    path("cart/add/<int:id>/", views.cart_add, name="cart_add"),
    path("cart/item_clear/<int:id>/", views.item_clear, name="item_clear"),
    path("cart/item_increment/<int:id>/", views.item_increment, name="item_increment"),
    path("cart/item_decrement/<int:id>/", views.item_decrement, name="item_decrement"),
    path("cart/cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart/cart-detail/", views.cart_detail, name="cart_detail"),
    # url of wishhlist
    path("Wishlistadd/<int:id>/", views.Addtowishlist, name="Wishlistadd"),
    path("Wishlist_detail/", views.Wishlist_detail, name="Wishlist_detail"),
    path(
        "Wishlist_item_delete/<int:id>/",
        views.Deletewishlistitem,
        name="Wishlist_item_delete",
    ),
    path("Wishlist_clear/", views.Wishlistclear, name="Wishlist_clear"),
   
]

app_name = "shop"

templates/cart/cart_detail.html
{% extends "base.html" %}
{% block content%}
{% load cart_tag %}

<div class="cart-main-area pt-100px pb-100px">
    <div class="container">
        <h3 class="cart-page-title">Your cart items</h3>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <form action="#">
                    <div class="table-content table-responsive cart-table-content">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Until Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for key,value in request.session.cart.items %}
                                <tr>
                                    <td class="product-thumbnail">
                                        
                                        <a href="#"><img class="img-responsive ml-15px" style="height:350px;width:250px;"  src="{{value.image}}"  alt="" /></a>
                                    </td>
                                    <td class="product-name"><a href="#">{{value.name}} </a></td>
                                    <td class="product-price-cart"><span class="amount">{{value.price}}</span></td>
                                    <td class="product-quantity">
                                        <div>
                                        <a class="cart_quantity_up" href="{% url 'shop:item_increment' value.product_id %}">+</a>
                                        <input class="cart-plus-minus-box" type="text" name="qtybutton" value="{{value.quantity}}" />
                                    </div>
                                    <div>
                                        <a class="cart_quantity_down" href="{% url 'shop:item_decrement' value.product_id %}"> - </a>
                                        
                                    </div>
                                    </div>
                                    </td>
                                    <td class="product-subtotal"> {{ value.price|multiply:value.quantity }}</td>
                                    <td class="product-remove">
                                        <a href="#"><i class="fa fa-pencil"></i></a>
                                        <a href="{% url 'shop:item_clear' key %}"><i class="fa fa-times">x</i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                             
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="cart-shiping-update-wrapper">
                                <div class="cart-shiping-update">
                                    <a href="{% url 'shop:index'%}">Continue Shopping</a>
                                </div>
                                <div class="cart-clear">
                                    <button>Update Shopping Cart</button>
                                    <a href="{% url 'shop:cart_clear' %}">Clear Shopping Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
              
                                  
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    </div>
                    <div class="col-lg-4 col-md-12 mt-md-30px">
                        <div class="grand-totall">
                            <div class="title-wrap">
                                <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                            </div>
                            <h5>Total products <span>{{request.session.cart|length}}</span></h5>
                            <div class="total-shipping">
                                <h5>Total shipping</h5>
                               
                            <h4 class="grand-totall-title">Grand Total <span>{{cart_total_amount}}</span></h4>
                            <a href="{% url 'shop:checkout-page' %}">Proceed to Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}