Ankurshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
import shop

# from shop import urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("shop/", include("shop.urls", namespace="shop")),
    path("accounts/", include("allauth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("api-auth/", include("rest_framework.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

# swagger imports
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views
from .views import (
    ProductViewSet,
    CategoryViewSet,
    OrderViewSet,
    AdressViewSet,
    WishlistViewSet,
    SearchListView,
)


schema_view = get_schema_view(
    openapi.Info(
        title="Ankurshop",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="Test License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

router = routers.DefaultRouter()
router.register(r"Products", ProductViewSet)
router.register(r"Category", CategoryViewSet)
router.register(r"Adress", AdressViewSet)
router.register(r"Order", OrderViewSet)
router.register(r"Wishlist", WishlistViewSet)
# router.register(r"search",ProductListView)


urlpatterns = [
    path("", include(router.urls)),
    path("search/", SearchListView.as_view(), name="search"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    #  path("gettoken/", obtain_auth_token),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # path('^swagger(?P<format>\.json|\.yaml)', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # path("wishlist",listWishlist.as_view(),name="wishlist"),
]

shop/urls.py
from django.urls import path
from .views import Index
from shop import views
from . import views
from shop import models


urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("Payment", views.Payment, name="Payment"),
    path("succes", views.Succes, name="succes"),
    path("search/", views.Search, name="search"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path("checkout", views.CheckoutCreateView.as_view(), name="checkout-page"),
    # urls for cart
    path("cart/add/<int:id>/", views.cart_add, name="cart_add"),
    path("cart/item_clear/<int:id>/", views.item_clear, name="item_clear"),
    path("cart/item_increment/<int:id>/", views.item_increment, name="item_increment"),
    path("cart/item_decrement/<int:id>/", views.item_decrement, name="item_decrement"),
    path("cart/cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart/cart-detail/", views.cart_detail, name="cart_detail"),
    # url of wishhlist
    path("Wishlistadd/<int:id>/", views.Addtowishlist, name="Wishlistadd"),
    path("Wishlist_detail/", views.Wishlist_detail, name="Wishlist_detail"),
    path(
        "Wishlist_item_delete/<int:id>/",
        views.Deletewishlistitem,
        name="Wishlist_item_delete",
    ),
    path("Wishlist_clear/", views.Wishlistclear, name="Wishlist_clear"),
   
]

app_name = "shop"

templates/Payment.html
{% extends 'base.html'%}
{% block content %}
{% load cart_tag %}

<div class="shopper-informations">
    <div class="row">

        <div class="col-sm-5 clearfix">
            <div class="bill-to">

                <div class="form-one">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}

                    </form>
                </div>
                <div class="form-two">
                    <form>


                    </form>
                </div>
            </div>
        </div>
        < </div>
    </div>
    <div class="review-payment">
        <h2>Review & Payment</h2>
    </div>

    <div class="table-responsive cart_info">
        <table class="table table-condensed">
            <thead>
                <tr class="cart_menu">
                    <td class="image">Item</td>
                    <td class="description"></td>
                    <td class="price">Price</td>
                    <td class="quantity">Quantity</td>
                    <td class="total">Total</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                {% for key,value in request.session.cart.items %}
                <tr>
                    <td class="cart_product">
                        <a href=""><img src="images/cart/one.png" alt=""></a>
                    </td>
                    <td class="cart_description">
                        <h4><a href="">{{value.name}}</a></h4>
                    </td>
                    <td class="cart_price">
                        <p>{{value.price}}</p>
                    </td>

                    <td class="cart_total">
                        <p class="cart_total_price">{{ value.price|multiply:value.quantity }}</p>
                    </td>
                    <td class="cart_delete">
                        <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
                    </td>
                </tr>
                {% endfor %}

                <td colspan="4">&nbsp;</td>
                <td colspan="2">
                    <table class="table table-condensed total-result">
                        <tr>
                            <td>Cart Sub Total</td>
                            <td>{{cart_total_amount}}</td>
                        </tr>

                        <tr>
                            <td>Total</td>
                            <td><span>{{cart_total_amount}}</span></td>
                        </tr>
                    </table>
                </td>
                </tr>
            </tbody>
        </table>
    </div>
    <tr>


</div>
</section>

<button id="rzp-button1">Pay</button>
<form action="{% url 'shop:succes'%}" method="post">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        var options = {
            "key": "rzp_test_a24CUgWec5REnl", // Enter the Key ID generated from the Dashboard
            // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
            "currency": "INR",

            "amount": "",
            "name": "Acme Corp",
            "description": "Test Transaction",
            "image": "https://example.com/your_logo",
            "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
            
            "callback_url": "http://ankurshop.herokuapp.com/shop/succes",
           
          
            "prefill": {
                "name": "Ankur zalaya",
                "email": "anzalaya@bestpeers.com",
                "contact": "8817022881"
            },
            "notes": {
                "address": "Razorpay Corporate Office"
            },
            "theme": {
                "color": "#3399cc"
            }
        };
        var rzp1 = new Razorpay(options);
        document.getElementById('rzp-button1').onclick = function (e) {
            rzp1.open();
            e.preventDefault();
        }
    </script>
</form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
</head>

<body class="p-3 mb-2 bg-secondary text-black" style="background-color: rgb(157, 177, 172) !important;">

  {% block body %}

  {% if messages %}

  <div>

    <strong>Messages:</strong>
    <ul>
      {% for message in messages %}
      <li>{{message}}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <div>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">AnkurShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'shop:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:cart_detail' %}">CART</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:Wishlist_detail' %}">Wishlist</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:contact' %}">CONTACTUS</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link" href="#">Hello {{user.username}}</a>
              
            
          </ul>
          <form class="d-flex" form action="search/" method="get">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query"
              id="query" />
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>


    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
      <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
      {% else %}



      {% endif %}
    </ul>
  </div>
  {% block content %}
  {% endblock %}
  {% endblock %}
  {% block extra_body %}
  {% endblock %}
</body>

</html>

templates/checkout.html
{% extends 'base.html'%}
{% block content %}
{% load cart_tag %}

<div class="shopper-informations">
    <div class="row">

        <div class="col-sm-5 clearfix">
            <div class="bill-to">

                <div class="form-one">
                    <form method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button type="submit" href="{% url 'shop:Payment'%}" value="Submit">Submit</button>
                    </form>
                </div>
                <div class="form-two">
                    <form>


                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="review-payment">
    <h2>Review & Payment</h2>
</div>

<div class="table-responsive cart_info">
    <table class="table table-condensed">
        <thead>
            <tr class="cart_menu">
                <td class="image">Item</td>
                <td class="description"></td>
                <td class="price">Price</td>
                <td class="quantity">Quantity</td>
                <td class="total">Total</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for key,value in request.session.cart.items %}
            <tr>
                <td class="cart_product">
                    <a href=""><img src="images/cart/one.png" alt=""></a>
                </td>
                <td class="cart_description">
                    <h4><a href="">{{value.name}}</a></h4>
                </td>
                <td class="cart_price">
                    <p>{{value.price}}</p>
                </td>
                <td class="cart_quantity">
                    <div class="cart_quantity_button">
                        <a class="cart_quantity_up" href="{% url 'shop:item_increment' value.product_id %}"> + </a>
                        <input class="cart_quantity_input" type="text" name="quantity" value="{{value.quantity}}"
                            autocomplete="off" size="2">
                        <a class="cart_quantity_down" href="{% url 'shop:item_decrement' value.product_id %}"> - </a>
                    </div>
                </td>
                <td class="cart_total">
                    <p class="cart_total_price">{{ value.price|multiply:value.quantity }}</p>
                </td>
                <td class="cart_delete">
                    <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
                </td>
            </tr>
            {% endfor %}

            <td colspan="4">&nbsp;</td>
            <td colspan="2">
                <table class="table table-condensed total-result">
                    <tr>
                        <td>Cart Sub Total</td>
                        <td>{{cart_total_amount}}</td>
                    </tr>

                    <tr>
                        <td>Total</td>
                        <td><span>{{cart_total_amount}}</span></td>
                    </tr>
                </table>
            </td>
            </tr>
        </tbody>
    </table>
</div>
<tr>

    </section>
    <div><a>placeorder</a></div>


    {% endblock %}

templates/contact.html
{% extends 'base.html'%}
{% block content%}
{% load static %}
{% load crispy_forms_tags %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn-primary" type="submit">SUBMIT</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content%}

{% load static %}


<div class="container" >
  <div class="row">
      {% for product in prod %}
      <div class="col-md-3">
          <div class="card" style="width: 18rem; margin-top: 20px; width: 100%;height:90%;">
          
            <img src="{{ product.image.url }}" class="card-img-top" style="height: 180px!important; background-clip: padding-box; object-fit: contain;">
       
              <div class="card-body">
                  <div class="card-title">
                      {{ product.name }}
                  </div>
                  <div class="card-text">
                  {{ product.price }}
                  </div>
                  <div>
                    <a href="{% url 'shop:cart_add' product.id %}" class="btn btn-primary" style="height:40px; width:95x;">AddCart</a>
      <a href="{% url 'shop:Wishlistadd' product.id%}" class="btn btn-primary" style="height:40px; width:125px;">AddWishlist</a>
                  </div>
              </div>
           </div>   
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

templates/navbar1.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">AnkurShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">CONTACTUS</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{%endblock%}

templates/search.html
{% extends 'base.html' %}
{%block content %}

{% for product in products %}
<tr>
    <td class="product-thumbnail">

        <a href="#">
            <img class="img-responsive ml-15px" style="height:350px;width:250px;" src="{{product.image.url}}"/>
        </a>
    </td>
    <td class="product-name"><a href="#">{{product.name}} </a></td>
    <td class="product-price-cart"><span class="amount">{{product.price}}</span></td>
    <div>
        <a href="{% url 'shop:cart_add' product.id %}" class="btn btn-primary" style="height:40px; width:100px;">Addtocart</a>
<a href="{% url 'shop:Wishlistadd' product.id%}" class="btn btn-primary" style="height:50px; width:100px;">Addtowishlist</a>
      </div>
</tr>
{% endfor %}

{% endblock %}

templates/thankyou.html
{% extends 'base.html'%}
{% block content %}
{% load cart_tag %}


<div class="review-payment">
    <h2>Thank you for Payment</h2>
</div>

<tr>

</section> 

    

{% endblock %}

templates/wish_detail.html
{% extends "base.html" %}

{% block content%}

{% load static %}

<h1>Hello {{user.username}}</h1>
<div class=" row"></div>
 
<a href="{% url 'shop:Wishlist_clear' %}"onclick="return confirm('Are you sure')">Clear Wishlist </a>

{% for Product in prod %}

<div class="column">
  {{Product.pubdate}}


  <div class="card" style="width: 18rem; ">
    <img class="card-img-top" src="{{ Product.product.image.url}}" alt="Card image cap">
    
    
    <div class="card-body">
      <h5 class="card-title" style="color:black;"> {{ Product.product.name}}</h5>
      <h5 class="card-title" style="color:black;">{{ Product.product.categorey}}</h5>
      <h6 class="card-price" style="color:black;">{{ Product.product.price}}Rs only</h6>
      <a href="{% url 'shop:cart_add' Product.product.id %}" class="btn btn-primary" style="height:40px; width:95x;">AddCart</a>
      <a  class="primary-btn" href="{% url 'shop:Wishlist_item_delete' Product.product.id %}"onclick="return confirm('Are you sure')">Delete</a>
    </div>
  </div>
</div>
</div>
{% endfor %}

</div>
{% endblock %}